config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :projects
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/pricing', to: 'static_pages#pricing'
  get '/blankpage', to: 'static_pages#blankpage'
  get '/login' => redirect('/users/sign_in')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new
    if user.client?
      can :manage, Project, user_id: user.id
    elsif user.admin?
      can :manage, :all
    else
      can :read, Project
      can :search, Project
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	validates :project_name, uniqueness: true

	def self.search(search)
		panme = ''
		#converts search to upcase to match project names in database. 
		if search
			search = search.upcase
		end

		#if search && where('project_name' => "#{search}").first.to_s.split("").count > 0 #Old way as quick proof of concept since I did not know there was a built-in function for checking if present. 
		#Checks if project exists in database. elsif not found, gives not found. else display the default project template. 
		#Remember to chance rocket and hash thing to be consistent after figuring out which is better. 
		if search && where('project_name' => "#{search}").first.present?
			where(project_name: "#{search}").first
		elsif search && where('project_name' => "#{search}").first.blank?
			where('project_name' => 'Project Not Found').first
		else
			where('project_name' => 'Project ID').first
		end
	end
end



#		if search && where('project_name' => "#{search}").first.present?
#			where(project_name: "#{search}").first
# => Remember to delete. 

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true
           #:optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
	rolify
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_many :projects, dependent: :destroy

	def admin?
		has_role?(:admin)
	end

	def client?
		has_role?(:client)
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	rescue_from CanCan::AccessDenied do |exception|
	  redirect_to root_url, alert: exception.message
	end
	
	def home
		
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  #before_action :sanitize_params, only: [:create]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.search(params[:search])
    @allProjects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end



  private
    def sanitize_params
      project_params[:progress] = project_params[:progress].to_i
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :description, :progress, :progress_description, :date_started, :last_updated, :eta, :project_type, :status, :approved)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def blankpage
  end

  def send_contact_email

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize_admin, only: :create

	def new
	end

	def create
	end

	def authorize_admin
	    return unless !current_user.admin?
	    redirect_to root_path, alert: 'Only Admins can register new users. '
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def boostrap_class(alert)
		{ success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
		  danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
	end

  def boostrap_class(alert)
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-success', warning: 'alert-warning',
      danger: 'alert-danger', alert: 'alert-danger' }[alert.to_sym]
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do

        concat message
      end)
    end
    nil
  end

  #Use this if you want the close button for flash messages. 
  #def flash_messages(_opts = {})
  #  flash.each do |msg_type, message|
  #    concat(content_tag(:div, message, class: "alert #{boostrap_class(msg_type.to_sym)} fade in") do
  #      concat(content_tag(:button, id: "close-button", class: "close", type: :button, data: { dismiss: 'alert' }, "aria-label" => :Close) do
  #        concat content_tag(:span, "&times;".html_safe, "aria-hidden" => true)
  #      end)
  #      concat message
  #    end)
  #  end
  #  nil
  #end

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Timeless Apps"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_copyright.html.erb
<!--a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a-->
<div id="copyright" class="hoc clear"> 

<p class="fl_left ta-pad-left">Copyright &copy; 2018 - Timeless Apps</p>
<p class="fl_right ta-pad-right"><a href="https://icons8.com/" title="Icons">Icons8, </a><a href="http://www.os-templates.com/" title="Free Website Templates">OS Templates</a></p>
</div>

app/views/layouts/_footer.html.erb
  <footer id="footer" class="hoc clear"> 
    <div class="one_third first">
      <h6 class="title">FAQ</h6>
      <ul class="nospace linklist">
        <li>
          <article>
            <h2 class="nospace font-x1 ta-font-corn">How long can a project take?</h2>
            <p class="font-xs block btmspace-10">Short answer: Weeks to Months+</p>
            <p class="nospace">Project timelines can vary. Small websites may take only a few weeks while large applications can span multiple months to complete. We provide estimates to customers as early as we can. </p>
          </article>
        </li>
      </ul>
    </div>
    <div class="one_third">
      <h6 class="title">Contact Information</h6>
      <ul class="nospace linklist contact">
        <li><i class="fa fa-map-marker"></i>
          <address>
          BC, Canada
          </address>
        </li>
        <li><i class="fa fa-phone"></i>###-###-####</li>
        <li><i class="fa fa-envelope-o"></i> support@timelessapps.com</li>
      </ul>
    </div>
    <div class="one_third ta-padding-right">
      <h6 class="title">FAQ</h6>
      <ul class="nospace linklist">
        <li>
          <article>
            <h2 class="nospace font-x1 ta-font-corn">Any monthly costs?</h2>
            <p class="font-xs block btmspace-10">Short answer: Starting at $0 depending on your preference. </p>
            <p class="nospace">We can provide guidance on third party hosting services. For websites that expect low traffic, free hosting options may be available. </p>
          </article>
        </li>
      </ul>
    </div>
  </footer>

app/views/layouts/_google-analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108237564-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-108237564-2');
</script>

app/views/layouts/_header.html.erb
<div>
  <header id="header" class="hoc clear ta-pad-left ta-fc-white ta-underline"> 
    <div id="logo" class="fl_left">
      <h1><%= link_to "Timeless Apps", root_path %></h1>
    </div>
    <nav id="mainav" class="fl_right">
      <ul class="clear ta-pad-right">
        <li class="active"><%= link_to "Home", root_path, :class => "drop" %></a>
          <ul>
            <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact</a></li>
          </ul>
        </li>

        <li><%= link_to "Pricing", pricing_path %></li>

        <li><%= link_to "Check Progress", projects_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "User ", "#", :class => "drop" %></a>
        <% else %>
          <li><%= link_to "Login", "#", :class => "drop" %></a>
        <% end %>
            <ul>
              <% if user_signed_in? %>
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
              <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% end %>
            </ul>
          </li>

      </ul>
    </nav>
  </header>
</div>

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
Template Name: Pobabini
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/javascripts' %>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<%= render 'layouts/google-analytics' %>
</head>
<body id="top">
  <div id="ta-home-bg" style="background-image: url(<%= yield(:bg_image) %>);" >
    <%= render 'layouts/header' %>
    <!-- The line under header -->
    <div class="wrapper row1">
    </div>

<%= yield %>
  </div>
<div class="wrapper row4">
  <%= render 'layouts/footer' %>
</div>

<div class="wrapper row5">
  <%= render 'layouts/copyright' %>
</div>


<!-- JAVASCRIPTS -->
    
</body>
</html>

app/views/projects/edit.html.erb
<div class="ta-project-form-wrapper">
	<h2>Editing Project</h2>

	<%= render 'form' %>

	<br>
	<div class="ta-action-buttons">
		<%= link_to 'Back', projects_path, class: "ta-btn-default" %>
		<%= link_to 'Show', @project, class: "ta-btn-info" %>
		<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "ta-btn-danger" %>
	</div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="ta-wrap-all">

<div class="ta-marg-top ta-search-wrap">
    <div class="center btmspace-50">
      <h3 class="font-x2 nospace ta-fc-white">Check Your Project's Progress</h3>
    </div>
  <form action="<%= projects_path %>" class="ta-center ta-search-space" method="get">
    <%= text_field_tag :search, nil, placeholder: "Enter Project ID (eg. TA001)", class: "ta-search-bar ta-center ta-fc-grey" %>
    <div class="ta-space"></div>
    <%= submit_tag 'Search', name: nil, class: "ta-btn-small"%>
  </form>
</div>

<!--
<%= link_to 'New Project', new_project_path %>
-->
<% if current_user && current_user.admin? %>
  <h2>Project List</h2>
  <div class="project-block">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
        <th class="col-md-2">Name</th>
          <th class="col-md-2 ta-description-box">Description</th>
          <th class="col-md-2">Creator</th>
          <th class="col-md-2">Approved</th>
          <th class="col-md-4 ta-action-buttons-header">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @allProjects.each do |project| %>
          <tr>
           <td class="col-md-2"><%= project.project_name %></td>
           <td class="col-md-2 ta-description-box"><%= project.description %></td>
           <td class="col-md-2"><%= project.user.try(:email) %></td>
           <td class="col-md-2"><%= project.approved %></td>
           <td class="col-md-4 ta-action-buttons">
              <%= link_to 'Show', project_path(project), class: "ta-btn-info" %>
              <%= link_to 'Edit', edit_project_path(project), class: "ta-btn-warning" %>
              <%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: "ta-btn-danger" %>
           </td>
       </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
<% end %>

  <div class="ta-proj-header ta-fc-white">
    <h1 class="ta-float-left"><%= @projects.project_name %>
    </h1>
    <span id="ta-status" class="ta-float-right">
      <%= @projects.status %>
    </span>
    <p class="ta-clear-both">
      <%= @projects.description %>
    </p>
    <br>
  </div>
  <div class="container ta-wrap ta-mid-scale ta-clear-both">
    <div class="ta-bar ta-clear-both">
        <ul class="progressbar">
          <% if @projects.progress > 0 %>
            <li class="active" id="p0 step1"></li>
          <% else %>
            <li id="p0 step1"></li>
          <% end %>

          <% if @projects.progress > 25 %>
            <li class="active" id="p25 step2"></li>
          <% else %>
            <li id="p25 step2"></li>
          <% end %>

          <% if @projects.progress > 50 %>
            <li class="active" id="p50 step3"></li>
          <% else %>
            <li id="p50 step3"></li>
          <% end %>

          <% if @projects.progress > 75 %>
            <li class="active" id="p75 step4"></li>
          <% else %>
            <li id="p75 step5"></li>
          <% end %>

          <% if @projects.progress >= 100 %>
            <li class="active" id="p100 step5"></li>
          <% else %>
            <li id="p100 step5"></li>
          <% end %>
        </ul>
    </div>

    <table class="ta-proj">
      <thead>
        <div class="ta-table-header">
          <tr>
            <th>Latest Update</th>
            <th><%= @projects.last_updated %></th>
          </tr>
        </div>
      </thead>

      <div class="ta-slide-down">
        <tbody>
            <tr>
              <td colspan="2"><%= @projects.progress_description %></td>
            </tr>
        </tbody>
      </div>
    </table>

    <br>

    <table class="ta-proj">
      <thead>
        <div class="ta-table-header">
          <tr>
            <th>Details</th>
            <th></th>
          </tr>
        </div>
      </thead>

      <div class="ta-slide-down">
        <tbody>
            <tr>
              <td>Estimated Completion Date</td>
              <td><%= @projects.eta %></td>
            </tr>
            <tr>
              <td>Date Started</td>
              <td><%= @projects.date_started %></td>
            </tr>
            <tr>
              <td>Status</td>
              <td><%= @projects.status %></td>
            </tr>
        </tbody>
      </div>
    </table>

  </div>
</div>

app/views/projects/new.html.erb
<div class="ta-project-form-wrapper">
	<h2>New Project</h2>

	<%= render 'form' %>

	<br>
	<div class="ta-action-buttons">
		<%= link_to 'Back', projects_path, class: "ta-btn-default" %>
	</div>
</div>

app/views/projects/show.html.erb
<%= flash_messages %>
<div class="ta-project-form-wrapper">
	<h2>Project</h2>

	<p>
	  <strong>Name:</strong>
	  <%= @project.project_name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  	$<%= @project.description %>
	</p>

	<p>
	  <strong>Name:</strong>
	  <%= @project.project_name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  	$<%= @project.description %>
	</p>


	<br>
	<%= link_to 'Back', projects_path, class: "ta-btn-default" %>
	<%= link_to 'Edit', edit_project_path(@project), class: "ta-btn-warning" %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<% provide(:bg_image,"/assets/bg2.jpg") %>
<!DOCTYPE html>
<html>
  <div id="pageintro" class="hoc clear ta-screen-height"> 
    <article class="ta-pad-left ta-fc-white">
      <h2 class="heading">About</h2>
      <p>Timeless Apps is a service that connects people directly with developers to create projects. Projects can range from simple websites to large web applications. We work with both individuals and small-medium businesses to find a solution that works for them.</p>
      <br>
      <p>We encourage the design of projects to be as simple and intuitive as possible. This way, the application can focus on the main objectives of the project and we won't have to spend as much time on training. </p>
      <br>
    </article>
  </div>
</html>

app/views/static_pages/blankpage.html.erb
<% provide(:title, "Blank Page") %>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>
<% provide(:bg_image,"/assets/bg2.jpg") %>
<!DOCTYPE html>
<html>
<!-- Top Background Image Wrapper -->
<%= flash_messages %>

<div class="ta-screen-height">
  <div id="pageintro" class="hoc clear"> 
    <article class="ta-pad-left ta-fc-white">
      <h2 class="heading">Simple and Effective</h2>
      <p class="ta-maxwidth-50">We create stunning websites and applications that drive success into your business. Our price ranges provide smaller businesses easier access to technical solutions. </p>
      <footer>
        <ul class="nospace inline pushright">
          <li><%= link_to "View Prices", pricing_path, :class => "btn" %></li>
          <li><%= link_to "Learn More", about_path, :class => "btn inverse" %></li>
        </ul>
      </footer>
    </article>

  </div>
</div>

<!-- End Top Background Image Wrapper -->

<div class="wrapper row3">
  <main class="hoc container clear ta-fc-grey"> 
    <!-- main body -->
    <div class="center btmspace-50">
      <h3 class="font-x2 nospace">Our Design</h3>
      <!-- p class="nospace">The principles that we follow to deliver the best user experience possible. </a>.</p-->
    </div>
    <ul class="nospace group services ta-pad-horizontal">
      <li class="one_third first">
        <article><a href="#"><i class="fa fa-paperclip"></i></a>
          <div class="ta-center ta-pad-bottom">
          <%= image_tag("icons/responsive.png", alt: "Responsive")%>
          </div>
          <h6 class="heading ta-center">Responsive</h6>
          <p>All of our websites are designed to be responsive for the most popular digital platforms today. <a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;">Your customers can view your content on their phones and tablets and still retain the smooth browsing experience that our websites are designed for. </span></p>
        </article>
      </li>
      <li class="one_third">
        <article><a href="#"><i class="fa fa-calculator"></i></a>
          <div class="ta-center ta-pad-bottom">
          <%= image_tag("icons/affordable.png", alt: "Affordable")%>
          </div>
          <h6 class="heading ta-center">Affordable</h6>
          <p>We keep our prices as low as possible to give smaller businesses better access to technical solutions.  <a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;">We work with our clients to make sure that their ideal designs can be achieved with minimal costs. </span></p>
          </article>
      </li>
      <li class="one_third">
        <article><a href="#"><i class="fa fa-pie-chart"></i></a>
          <div class="ta-center ta-pad-bottom">
          <%= image_tag("icons/intuitive.png", alt: "Intuitive")%>
          </div>
          <h6 class="heading ta-center">Intuitive</h6>
          <p>
          Our websites and apps are designed with user experience as a top priority. <a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;">We keep our layouts simple and concise to deliver a smooth and intuitive experience. </span></p>
        </article>
      </li>
      <li class="one_third first">
        <article><a href="#"><i class="fa fa-recycle"></i></a>
          <div class="ta-center ta-pad-bottom">
          <%= image_tag("icons/secure.png", alt: "Secure")%>
          </div>
          <h6 class="heading ta-center">Secure</h6>
          <p>Websites that we deliver are always secured with trusted and verified SSL certificates upon completion. <a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;">Visitors can also feel re-assured that their connection is encrypted with some of the most robust cyphersuits and protocols today. </span></p>
        </article>
      </li>
      <li class="one_third">
        <article><a href="#"><i class="fa fa-code-fork"></i></a>
          <div class="ta-center ta-pad-bottom">
          <%= image_tag("icons/reliable.png", alt: "Reliable")%>
          </div>
          <h6 class="heading ta-center">Reliable</h6>
          <p>We use components that have been proven to be reliable and consistent over time.<a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;"> Along with our rigorous testing processes, this minimizes the chances of our clients experiencing technical defect that naturally arise from experimental technology. </span></p>
        </article>
      </li>
      <li class="one_third">
        <article><a href="#"><i class="fa fa-cogs"></i></a>
          <div class="ta-center">
          <%= image_tag("icons/specialized.png", alt: "Specialized")%>
          </div>
          <h6 class="heading ta-center">Specialized</h6>
          <p>The customized solutions we create are designed to be focused specifically on what your business needs. <a class="ta-toggle-near ta-cursor"> More&raquo;</a> <span class="ta-span-near" style="visibility: hidden;">We keep the design simple and the costs low, because you only pay for what you need. </span></p>
        </article>
      </li>
    </ul>
    <!-- Main Body -->
    <div class="clear"></div>
  </main>
</div>

<!--div class="wrapper"-->
  <!-- Testimony Section -->
  <!--div class="split clear" style="background-image:url('/assets/bg2.jpg');">
    <section class="box"> 
      <div class="btmspace-50">
        <p class="nospace"><a href="#">Featured Testimony</a></p>
        <h2 class="heading">Quote</h2>
      </div>
      <div class="testimonial">
        <figure class="clear"><img src="images/demo/60x60.png" alt="">
          <figcaption><strong>Person</strong><br>
            <em>Professional Conman, Company Name</em></figcaption>
        </figure>
        <p>"Quote"</p>
      </div>
    </section>
  </div>
</div-->

  <div class="wrapper ta-bg-black">
    <!-- How it works section -->
    <div class="ta-section-black">
      <div class="ta-section-header">Getting Started</div>
      <div class="ta-section-wrapper">
        <div class="ta-section-paragraph ta-margin-left">
          <%= image_tag("icons/submit.png", alt: "Secure", class: "ta-step-icon" )%>
          <p class="ta-section-paragraph-title">1. Submit Request </p>
          <p class="ta-section-paragraph-text">You can submit a request for a project <a href="mailto:support@timelessapps.com?subject=Project%20Request&body=Project%20Type%20%28Simple%20Website%2C%20Full%20Website%2C%20Web%20Application%29%3A%0D%0A%0D%0AProject%20Description%3A%0D%0A">here</a>. We can also be contacted <a href="/contact" >here</a>. </p>
        </div>
        <div class="ta-section-paragraph ta-margin-left">
          <%= image_tag("icons/review.png", alt: "Secure", class: "ta-step-icon" )%>
          <p class="ta-section-paragraph-title">2. Review Request </p>
          <p class="ta-section-paragraph-text">We will review the request and reach out to you to confirm the details. </p>
        </div>
        <div class="ta-section-paragraph ta-margin-left">
          <%= image_tag("icons/work.png", alt: "Secure", class: "ta-step-icon" )%>
          <p class="ta-section-paragraph-title">3. Work on Project</p>
          <p class="ta-section-paragraph-text">Once in progress, you can check on the status of the project <a href="/projects">here</a>. </p>
        </div>
        <div class="ta-section-paragraph ta-margin-left">
          <%= image_tag("icons/deliver.png", alt: "Secure", class: "ta-step-icon" )%>
          <p class="ta-section-paragraph-title">4. Deliver Project</p>
          <p class="ta-section-paragraph-text">When completed, we will contact you and provide instructions on using the product. </p>
        </div>
        <span class="ta-stretch"></span>
      </div>
    </div>
  </div>

  <div class="wrapper row3">
    <div class="hoc container clear ta-fc-grey"> 
      <div class="center btmspace-50">
        <h3 class="font-x2 nospace">Check your progress</h3>
        <p class="nospace">We keep track of the progress of all of our projects. Simply enter your project ID and search to check the progress. </p>
      </div>
    <form action="<%= projects_path %>" class="ta-center ta-search-space" method="get">
      <%= text_field_tag :search, nil, placeholder: "Enter Project ID (eg. TA001)", class: "ta-search-bar ta-center ta-fc-grey" %>
      <div class="ta-space"></div>
      <%= submit_tag 'Search', name: nil, class: "ta-btn-small"%>
    </form>
      <div class="clear"></div>
    </div>
  </div>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>